// Code generated by protoc-gen-go.
// source: messages/ghResponse/ghList.proto
// DO NOT EDIT!

/*
Package ghResponse is a generated protocol buffer package.

It is generated from these files:
	messages/ghResponse/ghList.proto

It has these top-level messages:
	List
*/
package ghResponse

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type List struct {
	User string        `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	List []*ListGhList `protobuf:"bytes,2,rep,name=list" json:"list,omitempty"`
}

func (m *List) Reset()                    { *m = List{} }
func (m *List) String() string            { return proto.CompactTextString(m) }
func (*List) ProtoMessage()               {}
func (*List) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *List) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *List) GetList() []*ListGhList {
	if m != nil {
		return m.List
	}
	return nil
}

type ListGhList struct {
	Name            string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	StargazersCount string `protobuf:"bytes,2,opt,name=stargazers_count,json=stargazersCount" json:"stargazers_count,omitempty"`
}

func (m *ListGhList) Reset()                    { *m = ListGhList{} }
func (m *ListGhList) String() string            { return proto.CompactTextString(m) }
func (*ListGhList) ProtoMessage()               {}
func (*ListGhList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *ListGhList) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListGhList) GetStargazersCount() string {
	if m != nil {
		return m.StargazersCount
	}
	return ""
}

func init() {
	proto.RegisterType((*List)(nil), "ghResponse.List")
	proto.RegisterType((*ListGhList)(nil), "ghResponse.List.ghList")
}

func init() { proto.RegisterFile("messages/ghResponse/ghList.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x52, 0xc8, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x4f, 0xcf, 0x08, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0xd5,
	0x4f, 0xcf, 0xf0, 0xc9, 0x2c, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x42, 0x48,
	0x28, 0x4d, 0x60, 0xe4, 0x62, 0x01, 0x49, 0x09, 0x09, 0x71, 0xb1, 0x94, 0x16, 0xa7, 0x16, 0x49,
	0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x42, 0xda, 0x5c, 0x2c, 0x39, 0x99, 0xc5, 0x25,
	0x12, 0x4c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0xe2, 0x7a, 0x08, 0x7d, 0x7a, 0x60, 0xe3, 0x20, 0xa6,
	0x06, 0x81, 0x15, 0x49, 0xb9, 0x73, 0xb1, 0x41, 0xf8, 0x20, 0xa3, 0xf2, 0x12, 0x73, 0x53, 0x61,
	0x46, 0x81, 0xd8, 0x42, 0x9a, 0x5c, 0x02, 0xc5, 0x25, 0x89, 0x45, 0xe9, 0x89, 0x55, 0xa9, 0x45,
	0xc5, 0xf1, 0xc9, 0xf9, 0xa5, 0x79, 0x20, 0x63, 0x41, 0xf2, 0xfc, 0x08, 0x71, 0x67, 0x90, 0x70,
	0x12, 0x1b, 0xd8, 0x95, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe9, 0x5d, 0x88, 0x0a, 0xc9,
	0x00, 0x00, 0x00,
}
