// Code generated by protoc-gen-go.
// source: services/list/list.proto
// DO NOT EDIT!

/*
Package services is a generated protocol buffer package.

It is generated from these files:
	services/list/list.proto

It has these top-level messages:
*/
package services

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google/api"
import ghResponse "stars-app/messages/ghResponse"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ListStarsService service

type ListStarsServiceClient interface {
	ListStars(ctx context.Context, in *ghResponse.List, opts ...grpc.CallOption) (*ghResponse.List, error)
}

type listStarsServiceClient struct {
	cc *grpc.ClientConn
}

func NewListStarsServiceClient(cc *grpc.ClientConn) ListStarsServiceClient {
	return &listStarsServiceClient{cc}
}

func (c *listStarsServiceClient) ListStars(ctx context.Context, in *ghResponse.List, opts ...grpc.CallOption) (*ghResponse.List, error) {
	out := new(ghResponse.List)
	err := grpc.Invoke(ctx, "/services.ListStarsService/ListStars", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ListStarsService service

type ListStarsServiceServer interface {
	ListStars(context.Context, *ghResponse.List) (*ghResponse.List, error)
}

func RegisterListStarsServiceServer(s *grpc.Server, srv ListStarsServiceServer) {
	s.RegisterService(&_ListStarsService_serviceDesc, srv)
}

func _ListStarsService_ListStars_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ghResponse.List)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListStarsServiceServer).ListStars(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.ListStarsService/ListStars",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListStarsServiceServer).ListStars(ctx, req.(*ghResponse.List))
	}
	return interceptor(ctx, in, info, handler)
}

var _ListStarsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.ListStarsService",
	HandlerType: (*ListStarsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListStars",
			Handler:    _ListStarsService_ListStars_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/list/list.proto",
}

func init() { proto.RegisterFile("services/list/list.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0x28, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0x2d, 0xd6, 0xcf, 0xc9, 0x2c, 0x2e, 0x01, 0x13, 0x7a, 0x05, 0x45, 0xf9, 0x25,
	0xf9, 0x42, 0x1c, 0x30, 0x19, 0x29, 0x99, 0xf4, 0xfc, 0xfc, 0xf4, 0x9c, 0x54, 0xfd, 0xc4, 0x82,
	0x4c, 0xfd, 0xc4, 0xbc, 0xbc, 0xfc, 0x92, 0xc4, 0x92, 0xcc, 0xfc, 0xbc, 0x62, 0x88, 0x3a, 0x29,
	0xad, 0xe2, 0x92, 0xc4, 0xa2, 0x62, 0xdd, 0xc4, 0x82, 0x02, 0xfd, 0xdc, 0xd4, 0xe2, 0xe2, 0xc4,
	0xf4, 0xd4, 0x62, 0xfd, 0xf4, 0x8c, 0xa0, 0xd4, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0xfd, 0xf4,
	0x0c, 0x1f, 0xb8, 0x99, 0x46, 0x11, 0x5c, 0x02, 0x20, 0x5e, 0x30, 0x48, 0x47, 0x30, 0xc4, 0x78,
	0x21, 0x17, 0x2e, 0x4e, 0xb8, 0x98, 0x90, 0x80, 0x1e, 0x42, 0xab, 0x1e, 0x48, 0x58, 0x0a, 0x43,
	0x44, 0x49, 0xb8, 0xe9, 0xf2, 0x93, 0xc9, 0x4c, 0xbc, 0x4a, 0x1c, 0xfa, 0x65, 0x86, 0x60, 0x07,
	0x5b, 0x31, 0x6a, 0x25, 0xb1, 0x81, 0x2d, 0x30, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x87, 0xb8,
	0x7e, 0x31, 0xd0, 0x00, 0x00, 0x00,
}
